### ISSUE TITLE
Add menu item for each addon

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-projects/amplicode-addons-demo-r2#4]
Now all menu items are shown in one level

I suggest to separate functionality by addons:

<img src="https://user-images.githubusercontent.com/73226373/144035337-9c2b1cb8-2c61-46f8-ba46-e5794ffdedc3.png" height="400"/>
not sure about audits

**Comment by lovtsovaik** [comment]
Now the menu items are opening simultaneously.
![image](https://user-images.githubusercontent.com/73226373/146742758-9793758a-ce1a-46cc-a1fe-b20c5cdfa2ca.png)

**Comment by artemglinov** [comment]
Grouping Demo Menu Items into "Application" and "Test screens" Submenus is provided in [this commit](https://github.com/jmix-projects/amplicode-addons-demo-r2/commit/3600030f103d5263558a787dc3e9080fba64f3e1)

**Comment by lovtsovaik** [comment]
done
![image](https://user-images.githubusercontent.com/73226373/147233546-394dd443-26bd-4f6c-a84f-3bc0f94a1321.png)
